# Generated by Django 3.1.7 on 2021-03-08 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('mode', models.CharField(choices=[('air', 'Air'), ('road', 'Road'), ('rail', 'Rail')], max_length=12)),
                ('description', models.TextField()),
                ('dest_terminals', models.ManyToManyField(to='browser.Terminal')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='browser.state')),
            ],
        ),
    ]
