# Generated by Django 3.1.7 on 2021-03-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
