# Generated by Django 3.1.7 on 2021-03-09 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0004_state_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='terminal_id',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
