# Generated by Django 3.1.7 on 2021-03-09 10:36

from django.db import migrations


def populate_states(apps, schema_editor):
    states = [
        'Abia',
        'Adamawa',
        'Akwa Ibom',
        'Anambra',
        'Bauchi',
        'Bayelsa',
        'Benue',
        'Borno',
        'Cross River',
        'Delta',
        'Ebonyi',
        'Enugu',
        'Edo',
        'Ekiti',
        'Gombe',
        'Imo',
        'Jigawa',
        'Kaduna',
        'Kano',
        'Katsina',
        'Kebbi',
        'Kogi',
        'Kwara',
        'Lagos',
        'Nasarawa',
        'Niger',
        'Ogun',
        'Ondo',
        'Osun',
        'Oyo',
        'Plateau',
        'Rivers',
        'Sokoto',
        'Taraba',
        'Yobe',
        'Zamfara',
    ]

    State = apps.get_model('browser', 'State')
    
    # special case for the FCT
    state = State.objects.create(name='Federal Capital Territory', state_id='fct')
    state.save()

    for state in states:
        state_name = state + ' State'
        state_id = state.lower().replace(' ', '_')
        state_obj = State.objects.create(name=state_name, state_id=state_id)
        state_obj.save()
    

class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_terminal_terminal_id'),
    ]

    operations = [
        migrations.RunPython(populate_states),
    ]
